#!/bin/bash
# Starts the Planopolis Moodle container.
#   web  (default) – install or upgrade Moodle if needed, then run Apache
#   cron           – run Moodle's scheduled tasks every minute
#   setup          – only install/upgrade and configure, then exit
set -euo pipefail

MOODLE_DIR="${MOODLE_DIR:-/var/www/moodle}"
DATAROOT="${MOODLE_DATAROOT:-/var/moodledata}"
RUNAS="${MOODLE_RUNAS:-www-data}"
: "${MOODLE_URL:?Set MOODLE_URL, e.g. https://quiz.planopolis.id}"
: "${DB_HOST:?}" "${DB_NAME:?}" "${DB_USER:?}" "${DB_PASS:?}"
DB_PORT="${DB_PORT:-5432}"
MODE="${1:-web}"

as_web() {
    if [ "$(id -u)" = "0" ] && [ "$RUNAS" != "root" ]; then
        su -s /bin/bash "$RUNAS" -c "$(printf '%q ' "$@")"
    else
        "$@"
    fi
}

php_str() { php -r 'echo var_export($argv[1], true);' -- "$1"; }

write_config() {
    cat > "$MOODLE_DIR/config.php" <<PHP
<?php  // Generated by entrypoint.sh from environment variables – do not edit inside the container.
unset(\$CFG);
global \$CFG;
\$CFG = new stdClass();
\$CFG->dbtype    = 'pgsql';
\$CFG->dblibrary = 'native';
\$CFG->dbhost    = $(php_str "$DB_HOST");
\$CFG->dbname    = $(php_str "$DB_NAME");
\$CFG->dbuser    = $(php_str "$DB_USER");
\$CFG->dbpass    = $(php_str "$DB_PASS");
\$CFG->prefix    = 'mdl_';
\$CFG->dboptions = ['dbpersist' => 0, 'dbport' => $(php_str "$DB_PORT"), 'dbsocket' => ''];
\$CFG->wwwroot   = $(php_str "${MOODLE_URL%/}");
\$CFG->dataroot  = $(php_str "$DATAROOT");
\$CFG->admin     = 'admin';
\$CFG->directorypermissions = 02777;
\$CFG->routerconfigured = true;
\$CFG->sslproxy  = $( [ "${MOODLE_SSLPROXY:-false}" = "true" ] && echo true || echo false );
\$CFG->reverseproxy = $( [ "${MOODLE_REVERSEPROXY:-false}" = "true" ] && echo true || echo false );
\$CFG->preventexecpath = true;
require_once(__DIR__ . '/lib/setup.php');
PHP
    chown "$RUNAS" "$MOODLE_DIR/config.php" 2>/dev/null || true
    chmod 640 "$MOODLE_DIR/config.php"
}

wait_for_db() {
    for i in $(seq 1 60); do
        if PGPASSWORD="$DB_PASS" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -tAc 'SELECT 1' >/dev/null 2>&1; then
            return 0
        fi
        echo "Waiting for database ($i)..."; sleep 2
    done
    echo "Database not reachable" >&2; exit 1
}

is_installed() {
    [ "$(PGPASSWORD="$DB_PASS" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -tAc \
        "SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'mdl_config'")" = "1" ]
}

# True once cli/setup.php has finished (it stores the competition course id at the end of step 3).
is_configured() {
    [ -n "$(PGPASSWORD="$DB_PASS" psql -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" -tAc \
        "SELECT value FROM mdl_config_plugins WHERE plugin = 'local_planopolis' AND name = 'courseid' AND value <> '0'" \
        2>/dev/null)" ]
}

run_setup() {
    echo "Configuring the Planopolis quiz platform..."
    as_web php public/local/planopolis/cli/setup.php \
        --timelimit="${QUIZ_TIMELIMIT:-90}" --lang="${SITE_LANG:-id}"
}

install_or_upgrade() {
    mkdir -p "$DATAROOT"; chown -R "$RUNAS" "$DATAROOT" 2>/dev/null || true
    write_config
    wait_for_db
    cd "$MOODLE_DIR"
    if is_installed; then
        echo "Moodle already installed – running upgrade (safe when nothing changed)."
        as_web php admin/cli/upgrade.php --non-interactive
        # A first start that was interrupted during the Planopolis setup is completed here.
        if ! is_configured; then
            run_setup
        fi
    else
        : "${ADMIN_PASS:?Set ADMIN_PASS for the first installation}"
        echo "Installing Moodle..."
        as_web php admin/cli/install_database.php --agree-license \
            --fullname="${SITE_FULLNAME:-Planopolis PWK 2026}" --shortname="${SITE_SHORTNAME:-Planopolis}" \
            --adminuser="${ADMIN_USER:-superadmin}" --adminpass="$ADMIN_PASS" \
            --adminemail="${ADMIN_EMAIL:-admin@example.com}"
        run_setup
    fi
}

case "$MODE" in
    web)
        install_or_upgrade
        exec apache2-foreground
        ;;
    setup)
        install_or_upgrade
        ;;
    cron)
        write_config
        wait_for_db
        # Wait until the first installation and the Planopolis setup have completed.
        until is_configured; do
            echo "Waiting for installation..."; sleep 10
        done
        cd "$MOODLE_DIR"
        while true; do
            as_web php admin/cli/cron.php || true
            sleep 60
        done
        ;;
    *)
        exec "$@"
        ;;
esac
